steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --destination=gcr.io/$PROJECT_ID/financeiro-salvacode:$COMMIT_SHA
      - --destination=gcr.io/$PROJECT_ID/financeiro-salvacode:latest
      - --cache=true
      - --cache-ttl=24h
      - --dockerfile=Dockerfile.prod

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - run
      - deploy
      - financeiro-salvacode
      - --image=gcr.io/$PROJECT_ID/financeiro-salvacode:$COMMIT_SHA
      - --region=us-east4
      - --platform=managed
      - --allow-unauthenticated
      - --port=5000
      - --network=default
      - --subnet=default
      - --vpc-egress=private-ranges-only
      - --memory=128Mi
      - --cpu=1
      - --max-instances=1
      - --min-instances=0
      - --concurrency=25
      - --set-env-vars=NODE_ENV=production
      - --set-secrets=DATABASE_URL=SF_DATABASE_URL:latest,SESSION_SECRET=SF_SESSION_SECRET:latest,SMTP_HOST=SF_SMTP_HOST:latest,SMTP_PORT=SF_SMTP_PORT:latest,SMTP_USER=SF_SMTP_USER:latest,SMTP_PASS=SF_SMTP_PASS:latest,SMTP_FROM_EMAIL=SF_SMTP_FROM_EMAIL:latest

options:
  logging: CLOUD_LOGGING_ONLY